repos:
  # Ruff for linting and formatting
  - repo: local
    hooks:
      # Run the formatter first.
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]
      # Run the linter after formatting.
      - id: ruff
        name: ruff
        args: [ --fix ]
        entry: ruff check
        language: system
        types: [python]

  # Mypy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', --show-error-codes]  # Adjust this based on your project needs
        additional_dependencies: ['types-requests', 'types-PyYAML']

  # Basic pre-commit hooks for common checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace  # Remove trailing whitespace
      - id: end-of-file-fixer  # Ensure files end with a newline
      - id: check-yaml  # Validate YAML files
      - id: check-merge-conflict  # Prevent committing unresolved merge conflicts
